### ISSUE TITLE
URL error in examples

### ISSUE THREAD

**Issue by jonbarrow** [pogosandbox/pogobuf#10]
Since the wiki in the readme leads to the outdated repo this was forked from, I checked the examples for some information on how to use this lib. However in both the `inventory` and `list-catchable-pokemon` examples, the error `Parameter "url" must be a string, not object` appears quite often. The `inventory` example returns many errors (including the URL one), however the `list-catchable-pokemon` example only has the URL error.

I found that the error only occurs in the `list-catchable-pokemon` while attempting to get the map objects:
```javascript
let mapObjects = await client.getMapObjects(cellIDs, Array(cellIDs.length).fill(0));
```

**Comment by niicojs** [comment]
Did you run example from this repo or from the outdated one?

**Comment by jonbarrow** [comment]
The examples I tried are from this repo, not the outdated one.

**Comment by niicojs** [comment]
I can't reproduce it

**Comment by jonbarrow** [comment]
You tagged this as `more info needed` but haven't told me what information you need. So then I'll just take a guess.

I am running Node version 8.1.3 with NPM version 5.3.0 on a Windows 10 machine, and to login I use Google rather than PTC. My steps I took are as follows:
1. Install both `pogobuf-vnext` and `node-pogo-protos-vnext`
2. Copy the example from https://github.com/pogosandbox/pogobuf/blob/master/examples/list-catchable-pokemon.js
3. Replace lat and lng with my current lat and lng
4. I removed ` hashingKey: 'hash key'` and set `useHashingServer` to false, since I cannot find any information here on where to find/make a hashing key or what the hashing server even is
5. Run the example

**Comment by niicojs** [comment]
ok, thanks for the info.

unfortunatly, there is currently no way to use the api without a (paid) hash key, so that is why it's not working.
Here is where you can find a hash key (I'm not affiliate with them, and yes it's a monopoly right now): https://hashing.pogodev.org

**Comment by jonbarrow** [comment]
Damn okay, thanks for the help.
