### ISSUE TITLE
Unsupported Encryption for version 0.69.1

### ISSUE THREAD

**Issue by csfragsta** [pogosandbox/pogobuf#13]
Hi, When I try to run the sample script from given examples, I get the following error:

(node:2000) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: operation timed out after 5296 ms, 5 tries with error: Unsupported encryption for version 0.69.1
(node:2000) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I am new to Pogo hashing and don't have much knowledge regarding this api. Kindly assist me what I am missing here.

**Comment by csfragsta** [comment]
Can Somebody Pls reply?

**Comment by niicojs** [comment]
you can't expect people to respond in a matter of minutes.
you are not using paid software.

that beeing said, you should read docs also:
- add `version: 8705` to your config
- update everything to be sure
