### ISSUE TITLE
HashServerError

### ISSUE THREAD

**Issue by simonh1000** [pogosandbox/pogobuf#14]
I copy and pasted from the example/inventory.js - in other words:

    const client = new pogobuf.Client({
        authType: 'google',
        username: process.env.UNAME,
        password: process.env.PWORD,
        hashingKey: 'hash key',
        useHashingServer: true,
    });

and ended up with

```
name: 'SignatureError: HashServerError',
     message: 'Invalid key sent to hashing server',
     status: 401,
     data: 'This IP has been temporarily banned!',
     retry: false
```

I guess I misunderstood something about `hashingkey`?

**Comment by niicojs** [comment]
you are missing: `version: 8705` but that shouldn't ban you.
I guess your hash key is wrong

**Comment by simonh1000** [comment]
Ah, thanks, and I have caught up with what this hashing key thing is. I only want to make 1 request per month so 3.95 is a bit excessive for my needs
