### ISSUE TITLE
Requests Taking Too Long

### ISSUE THREAD

**Issue by TheCrabity** [pogosandbox/pogobuf#16]
Have been direct debugging:
> this.tryCallRPC
https://github.com/pogosandbox/pogobuf/blob/master/pogobuf/pogobuf.client.js#L530

And have been getting response times for 2-6 seconds. This happens with or without a proxy:
![image](https://user-images.githubusercontent.com/22338421/35851555-95c19bba-0ae5-11e8-847a-52a5dd8855a6.png)

These appear to be taking much longer than what would be expected?

**Comment by niicojs** [comment]
Did you find the cause?

**Comment by TheCrabity** [comment]
Yes. OVH network issues hit my server the other day. Once corrected, it fixed this as well. Thanks for checking in!
