### ISSUE TITLE
Return a more suitable error when incorrect password is provided

### ISSUE THREAD

**Issue by ashleykleynhans** [pogosandbox/pogobuf#7]
Currently when an incorrect password is provided to the PTC login, the following error is returned:

Error: Unable to parse token in response from PTC login.

Since PTC is typically very unstable, this error can lead one to assume that there are issues with PTC rather than with your actual password.

It would be great if an error could be returned to indicate that the login failed due to incorrect credentials being provided if possible.

**Comment by niicojs** [comment]
I've just published 2.0.3 which should be (a bit) better. Tell me if that works for you.

**Comment by ashleykleynhans** [comment]
Its perfect, thanks so much!

**Error: Invalid PTC login or password.**
